command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port=8000"
  - "--server.address=0.0.0.0"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: GOLD_CATALOG
    value: "dilshad_shawki"
  - name: GOLD_SCHEMA
    value: "geospatial"
  - name: GENIE_SPACE_ID
    value: ""
